import React from 'react';
import PageHeader from '../components/PageHeader';

const Investments = () => {
    return (
        <>
            <PageHeader title="Investments" />
            <section className="padded">
                <div className="container">
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi quisquam accusantium totam aspernatur sit consequuntur distinctio atque, voluptas deserunt officia quaerat impedit vel magni debitis adipisci commodi aliquam minus. Nam praesentium quibusdam unde ad sit, dicta itaque! Odio quia illum quod exercitationem commodi, error at obcaecati odit eum cupiditate ducimus maxime, sit ut consectetur quaerat alias, nulla fugiat magnam? Placeat id veritatis est tempora deserunt reprehenderit delectus nam nisi nemo illum, magni doloribus eum accusamus! Inventore expedita mollitia adipisci, ipsa, pariatur sapiente, minus saepe rem eaque repudiandae natus dicta asperiores laborum quidem hic repellendus odio blanditiis? Nemo, quod! Ex nobis eligendi dolor saepe iure, distinctio eos adipisci laboriosam incidunt vitae repudiandae quidem temporibus officiis obcaecati fugiat labore sit illo minima.</p>
                    <p>Maiores cum magnam reiciendis voluptatem voluptate minima modi tempore quaerat neque aperiam aspernatur velit, ut labore pariatur libero molestias fugit cupiditate? Quidem mollitia deleniti tenetur voluptatem ratione fugiat? Illum quis molestiae quidem. Voluptates repudiandae, ratione aliquam earum culpa facere eaque cupiditate maxime consequuntur nemo quisquam enim vitae maiores sint voluptate dolor, laborum blanditiis totam molestias perspiciatis distinctio hic possimus ea? Ipsum esse, fugit, voluptatem minus assumenda ipsam laborum consequuntur corporis, velit molestiae amet beatae dolorum quisquam accusantium temporibus cum neque magni officiis totam itaque reiciendis? Nobis amet laboriosam pariatur nisi modi eos cupiditate natus quia similique, molestias consequatur, dolorum reprehenderit. Repudiandae earum voluptatem, tenetur tempore ipsum adipisci, unde iure eius temporibus, consectetur assumenda suscipit aperiam necessitatibus aspernatur hic ducimus! Eaque.</p>
                    <p>Consequuntur hic impedit eligendi pariatur? Repellendus distinctio veniam quaerat fuga placeat quod necessitatibus, ab cupiditate eius beatae. Fuga itaque velit asperiores praesentium molestias ratione distinctio dolor aspernatur est, maiores consequatur necessitatibus excepturi accusamus nisi nostrum autem error. Unde voluptatum repellendus quas tempora eius voluptas fuga. Provident corrupti expedita recusandae tempore ullam iure iste vero in beatae, tenetur, quo voluptates cupiditate doloremque inventore perspiciatis laborum, quaerat veritatis consequuntur numquam! Assumenda est nihil, praesentium impedit cupiditate nam. Aliquam vitae ipsam eveniet voluptates ab fugiat nihil ducimus! Cupiditate molestiae iusto, facilis dicta corrupti esse quam, dolorem assumenda corporis sed voluptatum dolore ducimus deserunt? Id distinctio dolorum nam ratione consequatur voluptatum porro itaque quisquam neque aliquam. Accusamus, cupiditate assumenda consectetur aut esse dolores quidem!</p>
                    <p>Vero amet magnam ratione eveniet illum minima consequatur illo sit? Eaque eius placeat minima veritatis, necessitatibus mollitia libero eos neque distinctio quibusdam, tempore, ipsum provident quia doloremque cum blanditiis soluta. Illum sequi officia aliquam odit ipsa omnis optio aliquid. Magnam animi ea aliquam vel deserunt expedita esse rerum aperiam maxime reiciendis reprehenderit quidem, consequatur doloremque, similique nemo libero ratione ab veritatis! Fuga distinctio natus ex aut. Praesentium quas rem doloremque autem vero quisquam dignissimos in voluptatum culpa accusamus incidunt rerum temporibus totam ea optio repudiandae similique exercitationem placeat sed cum ad ipsam, doloribus, nobis quaerat! Suscipit, quasi ratione. Nesciunt culpa vero cum in eius magnam id non. Aperiam fugiat ipsam officiis. Distinctio veniam perspiciatis nisi, eaque dolorem porro non optio?</p>
                    <p>Error, odio quo mollitia provident magni voluptas repellat nostrum! Explicabo magnam, distinctio error reiciendis doloremque rerum praesentium? Aliquam deserunt a est maxime delectus accusantium ratione nesciunt nostrum incidunt veritatis quasi magni enim ab labore perspiciatis, exercitationem hic dolore laborum consectetur odio modi! Dicta repudiandae nam, similique hic aspernatur suscipit ipsam dolores velit quae temporibus modi autem quos maxime inventore. Et dignissimos voluptatem a sunt tempora deserunt quae molestiae iste quod sit consectetur, corrupti accusamus perspiciatis nobis cumque maiores nam laborum voluptates ipsa quibusdam distinctio reiciendis. Libero sit, ipsam facere voluptatem sapiente molestiae eligendi eveniet veniam assumenda at officia nulla alias, perspiciatis error ut eaque reiciendis a sequi magnam nihil aperiam dicta! Unde dolores eos itaque explicabo, earum expedita accusamus voluptates!</p>
                </div>
            </section>
        </>
    )
}

export default Investments;